#!/bin/sh /etc/rc.common

START=99

enabled="$(uci get autoua2f.config.enabled)"
handle_fw="$(uci get autoua2f.config.handle_fw)"
disable_connmark="$(uci get autoua2f.config.disable_connmark)"

start() {
    uci set ua2f.enabled.enabled=$enabled
    uci set ua2f.firewall.handle_fw=$handle_fw
    uci set ua2f.firewall.handle_tls=$handle_fw
    uci set ua2f.firewall.handle_intranet=$handle_fw
    uci set ua2f.firewall.handle_mmtls=$handle_fw
    uci set ua2f.main.disable_connmark=$disable_connmark
    uci set ua2f.main.custom_ua="$(uci get autoua2f.config.Custom_UA)"
    uci commit ua2f
    if [ "$enabled" = "1" ]; then
    	/etc/init.d/ua2f stop
	/etc/init.d/ua2f start
	logger "防检测已开启"
    elif [ "$enabled" = "0" ]; then
	/etc/init.d/ua2f stop
	logger "防检测已停止"
    fi
}

stop() {
    /etc/init.d/ua2f stop
    logger "防检测已停止"
}
