#!/bin/sh /etc/rc.common

START=99

enabled="$(uci get autoua2f.config.enabled)"

start() {
    uci set ua2f.enabled.enabled=$enabled
    uci set ua2f.firewall.handle_fw=$enabled
    uci set ua2f.firewall.handle_tls=$enabled
    uci set ua2f.firewall.handle_intranet=$enabled
    uci set ua2f.firewall.handle_mmtls=$enabled
    uci set ua2f.main.custom_ua="$(uci get autoua2f.config.Custom_UA)"
    uci commit ua2f
    if [ "$enabled" = "1" ]; then
    	/etc/init.d/ua2f stop
	/etc/init.d/ua2f start
	logger "ua2f已开启"
    elif [ "$enabled" = "0" ]; then
	/etc/init.d/ua2f stop
	logger "ua2f已停止"
    fi
}

stop() {
    /etc/init.d/ua2f stop
    logger "ua2f已停止"
}
