#!/bin/sh /etc/rc.common

START=99

dusr_bata() {
	log_file="/tmp/log/shanligong.log"
    ENABLED="$(uci get shanligong.config.enabled)"
}

start() {
	dusr_bata
    if [ "$ENABLED" -eq 1 ]; then
		pgrep -f /etc/nettask/ping.sh | xargs kill -9 >/dev/null 2>&1
		sh /etc/nettask/ping.sh &
	else
		pgrep -f /etc/nettask/ping.sh | xargs kill -9 >/dev/null 2>&1
	fi


stop() {
	echo "Error"
}

reload() {
	stop
	start
}
