#!/bin/sh /etc/rc.common

START=99

enabled="$(uci get autoua.config.enabled)"
handle_fw="$(uci get autoua.config.handle_fw)"
handle_intranet="$(uci get autoua.config.handle_intranet)"
handle_tls="$(uci get autoua.config.handle_tls)"
handle_mmtls="$(uci get autoua.config.handle_mmtls)"

start() {
    uci set ua.enabled.enabled=$enabled
    uci set ua.firewall.handle_fw=$handle_fw
    uci set ua.firewall.handle_tls=$handle_tls
    uci set ua.firewall.handle_intranet=$handle_intranet
    uci set ua.firewall.handle_mmtls=$handle_mmtls
    uci set ua.main.custom_ua="$(uci get autoua.config.Custom_UA)"
    uci commit ua
    if [ "$enabled" = "1" ]; then
    	/etc/init.d/ua stop
	/etc/init.d/ua start
	logger "防检测已开启"
    elif [ "$enabled" = "0" ]; then
	/etc/init.d/ua stop
	logger "防检测已停止"
    fi
}

stop() {
    /etc/init.d/ua stop
    logger "防检测已停止"
}
