#!/bin/sh

# Copyright 2020 BlackYau <blackyau426@gmail.com>
# GNU General Public License v3.0

# Place in /etc/hotplug.d/iface

enable=$(uci get sdutlogin.@login[0].enable)
[ $enable -eq 0 ] && exit 0

dir="/tmp/log/sdutlogin/" && mkdir -p ${dir}
logfile="${dir}sdutlogin.log"
ua="User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"

function isonline(){
	local captiveReturnCode=`curl -s -I -m 10 -o /dev/null -s -w %{http_code} http://www.google.cn/generate_204`
	if [ "$captiveReturnCode" = "204" ]; then
		return
	fi
	false
}

function up(){
	if isonline; then
		echo "$(date "+%Y-%m-%d %H:%M:%S"): 您已连接到网络(hotplug)" >> ${logfile}
		sleep 1 && return
	fi

	# Login
	curl -m 5  https://www.baidu.com/ > baidu.com

	check_status=`curl -I -m 5 -s -w "%{http_code}\n" -o /dev/null www.baidu.com`

	echo $check_status >> ${logfile}

	if [[ $check_status != 200  ]]

	then

   	 echo "Not signed in yet" >> ${logfile}
   	 ip=$(ubus call network.interface.wan status | grep '\"address\"\: \"' | grep -oE '([0-9]{1,3}.){3}.[0-9]{1,3}')

    curl "http://172.16.253.121/quickauth.do?userid=${username}&passwd=${password}&wlanuserip=${ip}&wlanacname=NFV-BASE-SGYD2&wlanacIp=172.16.253.114&ssid=&vlan=1116&mac=c0%3A18%3A50%3Af9%3Ac1%3Ac5&version=0&portalpageid=2&timestamp=1730174830854&portaltype=0&hostname=HuaWei&bindCtrlId=&validateType=0&bindOperatorType=2&sendFttrNotice=0"
	else

 	   echo "Already logged in" >> ${logfile}

	fi
}

if [ "$INTERFACE" = wan ]; then  # Place in /etc/hotplug.d/iface
	if [ "$ACTION" = ifup ]; then
		echo "$(date "+%Y-%m-%d %H:%M:%S"): 检测到 WAN 口状态变化,准备尝试拨号" >> ${logfile}
		username=$(uci get sdutlogin.@login[0].username)
		password=$(uci get sdutlogin.@login[0].password)
		up
	fi
fi
exit 0